"""Generate manuscript results and a value-to-artifact ledger. No invented data."""
from pathlib import Path
import argparse,hashlib,json,sys
import numpy as np
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'src'))
from iot_repair.experiment import json_save
p=argparse.ArgumentParser();p.add_argument('--draft',action='store_true');args=p.parse_args()
out=ROOT/'paper/generated';out.mkdir(parents=True,exist_ok=True)
cache={};ledger=[];outputs={};section=''
NAMES=['synthetic_32_linear','synthetic_32_nonlinear','synthetic_64_nonlinear','intel','skab']
SHORT=['S32L','S32N','S64N','Intel','SKAB']
MAIN='results/analysis.json';DESIGN='results/dataset_summary.json';CONF='results/confidence_comparisons.json'

def read(path):
    if path not in cache:cache[path]=json.loads((ROOT/path).read_text())
    return cache[path]
def get(path,*keys):
    v=read(path)
    for k in keys:v=v[k]
    return v

def num(path,*keys,d=3,mult=1):
    value=get(path,*keys);rendered='N/A' if value is None else f'{value*mult:.{d}f}'
    ledger.append(dict(output=section,source=path,json_path=list(keys),value=value,multiplier=mult,rendered=rendered))
    return rendered

def derived(value,sources,operation,d=3):
    rendered=f'{value:.{d}f}';ledger.append(dict(output=section,sources=sources,operation=operation,value=float(value),rendered=rendered));return rendered

def write(name,text):
    (out/name).write_text('% Generated by scripts/make_paper.py from saved results.\n'+text+'\n');outputs[name]=hashlib.sha256((out/name).read_bytes()).hexdigest()
def metric(name,method='proposed',kind='observation',key='window_ap',d=3):return num(MAIN,name,'tracks',kind,'methods',method,key,d=d)
def base(name):return get(MAIN,name,'tracks','observation','primary_comparator')
def ci(path,*keys,d=3):return '['+num(path,*keys,'interval',0,d=d)+', '+num(path,*keys,'interval',1,d=d)+']'
def abl(name,variant,kind='observation',key='window_ap'):
    path=f'results/ablations/{name}/analysis.json'
    if not (ROOT/path).exists() or variant not in read(path):
        if args.draft:return r'\textit{pending}'
        raise RuntimeError('Incomplete ablation '+name+'/'+variant)
    return num(path,variant,'metrics',kind,key)
def require(path):
    if not (ROOT/path).exists():
        if args.draft:return False
        raise RuntimeError('Missing required result '+path)
    return True

def table(caption,label,columns,rows,wide=True):
    env='table*' if wide else 'table'
    return '\\begin{'+env+'}[t]\n\\centering\\small\n\\caption{'+caption+'}\\label{'+label+'}\n\\begin{tabular}{'+columns+'}\n\\toprule\n'+'\n'.join(rows)+'\n\\bottomrule\n\\end{tabular}\n\\end{'+env+'}'

def row(label,values):return label+' & '+' & '.join(values)+r' \\'

for name in NAMES:
    assert get(MAIN,name,'tracks','observation','methods','proposed','windows')>0
    if not args.draft:require(f'results/ablations/{name}/complete.json');require(f'results/robustness/{name}/analysis.json')
if not args.draft:
    for path in ['results/native/skab/analysis.json','results/latency_scaling.json','results/audits/portable_models.json','results/interface/browser_verification.json','results/graph/persistence_audit.json']:require(path)
section='numbers.tex'
write(section,r'\newcommand{\StudyStatus}{'+(r'\begin{center}\textcolor{red}{Layout draft. Secondary results still running.}\end{center}' if args.draft else '')+'}')
section='abstract_results.tex'
write(section, f"PCA outperformed the proposed score on the primary observation-detection endpoint in four configurations, with an inconclusive difference on Intel. In the 32-channel nonlinear configuration, attribution precision among the highest-ranked 10\\% of screened candidates was {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods','proposed','candidate_risk_coverage',0,'precision')} versus {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods',base('synthetic_32_nonlinear'),'candidate_risk_coverage',0,'precision')} for the selected PCA comparator. The paired difference interval was {ci(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.1')}. This benefit reversed at broader coverage. No clear association-detection advantage was established.")
section='datasets_table.tex';rows=[r'Configuration & Channels / sources & Split unit & Train windows & Dev / cal / test bases & Test missing \\',r'\midrule']
for name,short in zip(NAMES,SHORT):
    rows.append(row(short,[num(DESIGN,name,'channels',d=0)+' / '+num(DESIGN,name,'physical_sources',d=0),
        'trajectory' if name.startswith('synthetic') else 'day' if name=='intel' else 'experiment',num(DESIGN,name,'splits','train','windows',d=0),
        ' / '.join(num(DESIGN,name,'splits',split,'base_windows_selected',d=0) for split in ['development','calibration','test']),num(DESIGN,name,'splits','test','missing_fraction',mult=100,d=1)+r'\%']))
prevalence=[get(DESIGN,n,'association_window_prevalence') for n in NAMES]
write(section,table('Executed partitions. S32L, S32N and S64N are configurations of one synthetic dataset. Each base supplies an unmodified and a corrupted window per eligible controlled task. Observation prevalence is 0.50. Association prevalence ranges from '+derived(min(prevalence),[DESIGN],'minimum association window prevalence')+' to '+derived(max(prevalence),[DESIGN],'maximum association window prevalence')+'. Missingness is measured before injected dropout. Native SKAB process events are evaluated separately.','tab:data','lclrrr',rows))
section='main_table.tex';rows=[row('Method or endpoint',SHORT),r'\midrule',r'\multicolumn{6}{l}{Observation window average precision} \\']
for title,method in [('PCA, current values','pca1'),('PCA, lag embedding','pca4'),('GDN','gdn'),('Diffusion residual','backbone'),('DiffAD adaptation','diffad'),('Deterministic repair','deterministic'),('Witness repair','proposed')]:
    vals=[]
    for name in NAMES:
        m=get(MAIN,name,'selection','pca','1' if method=='pca1' else '4') if method in ('pca1','pca4') else method
        vals.append(abl(name,m) if m=='deterministic' else metric(name,m))
    rows.append(row(title,vals))
rows.append(row(r'Paired difference, 95\% interval', [r'\shortstack{'+num(MAIN,n,'tracks','observation','paired_difference','difference')+r'\\{}'+ci(MAIN,n,'tracks','observation','paired_difference')+'}' for n in NAMES]))
rows.extend([r'\midrule',r'\multicolumn{6}{l}{Association window average precision} \\'])
for title,m in [('Direct edge residual','edge_residual'),('Deterministic repair','deterministic'),('Witness repair','proposed')]:rows.append(row(title,[abl(n,m,'association') if m=='deterministic' else metric(n,m,'association') for n in NAMES]))
rows.append(row(r'Paired difference, 95\% interval',[r'\shortstack{'+num(MAIN,n,'tracks','association','paired_difference','difference')+r'\\{}'+ci(MAIN,n,'tracks','association','paired_difference')+'}' for n in NAMES]))
rows.extend([r'\midrule',row('Observation top-one attribution',[metric(n,key='top1') for n in NAMES]),row('Observation screening recall',[metric(n,key='screening_recall') for n in NAMES])])
write(section,table('Controlled-fault results. Differences are witness repair minus the comparator selected on development data, PCA for observations and direct residuals for associations. Both PCA variants are reported. GDN, PCA and the residual diffusion detectors have no stored-association output, so that task is not applicable to them. Attribution rows describe witness repair and include screening misses. Intervals resample whole source blocks.','tab:main','lrrrrr',rows))
section='results_text.tex'
text=r'Table~\ref{tab:main} answers the primary detection question. The proposed score did not improve observation detection over the development-selected comparator. Its paired average-precision differences were negative with intervals excluding zero in the three synthetic configurations and SKAB. The Intel interval included zero. These results favor retaining PCA as the inexpensive first detector. Nonlinear responses alone did not make the linear baseline ineffective.'+'\n\n'
text+=f"There was a narrower review benefit in S32N. At 10\\% screened-candidate coverage, precision was {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods','proposed','candidate_risk_coverage',0,'precision')} for witness repair and {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods',base('synthetic_32_nonlinear'),'candidate_risk_coverage',0,'precision')} for PCA. The paired precision difference was {num(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.1','difference')} with interval {ci(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.1')}. At 25\\% coverage the difference was {num(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.25','difference')} with interval {ci(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.25')}. The advantage therefore concerns a limited review budget, not more complete detection. These secondary intervals are descriptive and are not adjusted for multiple comparisons.\n\n"
text+=f"On the same S32N candidate population, fitted-probability Brier loss was {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods','proposed','probability_evaluation','brier')} versus {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods',base('synthetic_32_nonlinear'),'probability_evaluation','brier')} for PCA. The paired difference interval was {ci(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','brier_main_minus_comparator')}. Lower probability error does not recover faults omitted by screening. Observation screening recall ranged from {derived(min(get(MAIN,n,'tracks','observation','methods','proposed','screening_recall') for n in NAMES),[MAIN],'minimum proposed observation screening recall')} to {derived(max(get(MAIN,n,'tracks','observation','methods','proposed','screening_recall') for n in NAMES),[MAIN],'maximum proposed observation screening recall')}.\n\n"
text+=r'Association differences all had intervals containing zero. The mask procedure supplies an inspectable alternative explanation but did not establish better association detection than direct prediction residuals. Marginally matched relation faults still had joint metadata shortcuts. The metadata-only classifier obtained ROC area '+num('results/audits/association_metadata.json','skab','metadata_only_roc_auc')+r' on SKAB. This limits claims about relation reasoning despite preserved degrees and attribute marginals.'+'\n\n'
text+=f"Calibration had finite resolution. Intel had only {num(MAIN,'intel','tracks','observation','methods','proposed','null_reference_units',d=0)} reference windows, so its minimum window tail was {num(MAIN,'intel','tracks','observation','methods','proposed','null_resolution')}. No configuration could raise a window alarm at the nominal 1\\% level. At 5\\%, observed false-positive fractions for witness repair were "+', '.join(num(MAIN,n,'tracks','observation','methods','proposed','operating_points',1,'fpr') for n in NAMES)+r' in table order. Figure~\ref{fig:confidence} keeps the measured families separate. The labeled probability fit and the null-tail test answer different questions.'
write(section,text)
section='ablation_table.tex';rows=[row('Score or inference variant',SHORT),r'\midrule']
for title,m in [('Selected score','proposed'),('Gain only','R_only'),(r'Fixed $\kappa=1,\lambda=0.2$','fixed_penalties'),('No spread penalty','no_uncertainty'),('No edit penalty','no_cost'),('Supervised terms','supervised_terms')]:rows.append(row(title,[metric(n,m) for n in NAMES]))
for title,v in [('Deterministic replacements','deterministic'),('No graph conditioning','no_graph'),('Visible witnesses (unsafe)','no_witness_separation'),('Channel groups (unsafe)','no_provenance_grouping'),('Count known copies (unsafe)','no_provenance_deduplication')]:rows.append(row(title,[abl(n,v) for n in NAMES]))
rows.append(r'\midrule')
rows.append(row(r'Selected $(\kappa,\lambda)$',['('+num(MAIN,n,'selection','kappa',d=2)+', '+num(MAIN,n,'selection','lambda',d=2)+')' for n in NAMES]))
write(section,table('Observation window average precision for the equation and inference ablations. Every variant uses the same test cases and its own reference scores on the common calibration blocks. Unsafe variants are diagnostics. Zero selected penalties produce identical rows by construction.','tab:ablation','lrrrrr',rows))
section='ablation_text.tex'
text=r'Table~\ref{tab:ablation} separates arithmetic correctness from predictive usefulness. Development selection set the edit penalty to zero in every configuration except Intel and set both penalties to zero in S32N. The positive Intel cost penalty did not change test average precision at the displayed precision. These findings do not support the claim that every score term is needed. A single-edge cost is constant within a fixed graph, so it cannot improve the order of edges in that window.'+'\n\n'
text+=f"The spread penalty had a practical threshold effect on controlled SKAB windows. Gain alone had false-positive fraction {num(MAIN,'skab','tracks','observation','methods','R_only','operating_points',1,'fpr')} at nominal 5\\%, compared with {num(MAIN,'skab','tracks','observation','methods','proposed','operating_points',1,'fpr')} for the selected score. Fault recall also fell from {num(MAIN,'skab','tracks','observation','methods','R_only','operating_points',1,'recall')} to {num(MAIN,'skab','tracks','observation','methods','proposed','operating_points',1,'recall')}. Conservatism here does not imply accurate diagnosis.\n\n"
if all((ROOT/f'results/ablations/{n}/complete.json').exists() for n in NAMES):
    text+=r'The deterministic comparison tests whether sampling alternative readings adds value beyond a conditional mean. Witness visibility and counted copies are deliberately invalid evidence procedures. Their scores are retained even when they improve a metric. Such improvement cannot validate the claimed separation or independent support. The Intel channel-group diagnostic further distinguishes physical devices from channels.'+'\n\n'
else:text+=r'\textcolor{red}{Secondary inference ablations are still running in this layout draft.}'+'\n\n'
text+=f"The production audit independently recomputed {num('results/audits/production_equations.json','candidates',d=0)} candidate scores from saved samples across {num('results/audits/production_equations.json','cases',d=0)} cases. The largest absolute arithmetic discrepancy was "+derived(get('results/audits/production_equations.json','max_absolute_error')*1e15,['results/audits/production_equations.json'],'maximum error multiplied by 10^15',d=2)+r'$\times10^{-15}$. This verifies implementation, not the research hypotheses. Figure~\ref{fig:equations} examines paired variants, sampling variability, contaminated conditioning and measured runtime.'
write(section,text)
section='native_text.tex';path='results/native/skab/analysis.json'
if require(path):
    d=read(path);methods=d['methods'];selected=base('skab')
    text=f"Native SKAB evaluation covered {num(path,'methods','gdn','windows',d=0)} windows from {num(path,'methods','gdn','experiments',d=0)} disjoint test experiments. GDN had process-window average precision {num(path,'methods','gdn','window_ap')}, event recall {num(path,'methods','gdn','event_recall')} and false-positive fraction {num(path,'methods','gdn','achieved_fpr')} at nominal 5\\%. Median delay among detected events was {num(path,'methods','gdn','median_detected_event_delay_seconds',d=1)} seconds, with {num(path,'methods','gdn','censored_events',d=0)} undetected events. It retained {num(path,'methods','gdn','process_alerts_retained_during_attribution_abstention',d=0)} process alerts while attribution abstained. These labels support no sensor-localization claim.\n"
    rows=[r'Method & Window AP & Event recall & False events/h \\',r'\midrule']
    for label,m in [('PCA, lag embedding',selected),('GDN','gdn'),('Diffusion residual','backbone'),('DiffAD adaptation','diffad')]:rows.append(row(label,[num(path,'methods',m,'window_ap'),num(path,'methods',m,'event_recall'),num(path,'methods',m,'false_alarm_events_per_hour',d=2)]))
    text+='\n'+table('Native SKAB process events. Thresholds come from the frozen calibration protocol. Event delay is measured at the actual decision time without point adjustment.','tab:native','lrrr',rows,False)
else:text=r'\textcolor{red}{Native SKAB process evaluation is pending in this layout draft.}'
write(section,text)
section='cost_text.tex';path='results/latency_scaling.json'
if require(path):
    runs=get(path,'runs');sources=[path,MAIN]
    for n in ['synthetic_32_nonlinear','synthetic_64_nonlinear']:
        assert len([r for r in runs if r['dataset']==n and r['tested_candidates']==8])==5
    seconds=[np.median([r['elapsed_seconds'] for r in runs if r['dataset']==n and r['tested_candidates']==8]) for n in ['synthetic_32_nonlinear','synthetic_64_nonlinear']]
    memory=max(r['peak_allocated_bytes'] for r in runs)/2**30
    text='On the existing RTX PRO 4500 Blackwell GPU, median warm inference for eight tested hypotheses was '+derived(seconds[0],sources,'median 32-channel warm runs, 8 candidates')+' s for S32N and '+derived(seconds[1],sources,'median 64-channel warm runs, 8 candidates')+' s for S64N. Peak allocated memory across the candidate-scaling runs was '+derived(memory,sources,'maximum allocated bytes / 2^30',d=2)+' GiB. Timings include transfer and score computation and exclude loading and database writes. They are throughput measurements for the saved window, not end-to-end service guarantees. '
    bt=get(MAIN,'synthetic_32_nonlinear','costs','baseline_timing');pca=bt[base('synthetic_32_nonlinear')]['inference_seconds_per_window']
    text+='The same configuration required '+derived(pca*1e3,[MAIN],'PCA inference seconds per window times 1000',d=3)+' ms per window for PCA and '+derived(bt['gdn']*1e3,[MAIN],'GDN ensemble batched inference seconds per window times 1000',d=3)+' ms for GDN in batched comparator evaluation. These baseline timings use a different batching regime and are reported as measured, not as a hardware-independent speedup. '
    training=[r for n in NAMES for r in get(MAIN,n,'costs','training')]
    text+='The final neural training records total '+derived(sum(r['gpu_hours'] for r in training),[MAIN],'sum final recorded neural training GPU hours',d=3)+' GPU hours, excluding tuning, pilot work and experiment inference. Decisions use a 32-sample stride, corresponding to 32 s for the simulator and SKAB and 160 min for Intel. This stride and the eight-step target interval limit temporal resolution.'
else:text=r'\textcolor{red}{Uncontended inference benchmarking is pending in this layout draft.}'
write(section,text)
section='network_caption.tex';b='results/graph/synthetic_32_nonlinear_illustration.json';case=get(b,'case')
write(section,'Saved S32N case from '+case['block'].replace('_',r'\_')+', samples '+num(b,'case','start',d=0)+' to '+num(b,'case','stop',d=0)+'. The '+case['fault']['family']+' reading fault was injected and its label provenance is recorded. Graph version '+r'\texttt{'+case['graph']['version']+'}'+'. Coordinates are fixed across panels. Arrows predict the labeled target at the stated lag in seconds. All highlighted sources and witnesses are retained. The context uses a stored-relation spanning forest and layout uses no fault labels. This selected illustration does not estimate performance.')
section='conclusion_results.tex'
write(section,r'The experiments support a bounded role for witness repair as a review mechanism. They do not support replacing PCA for broad observation detection or direct relation residuals for association detection. A measured benefit appears at a small review budget in one nonlinear synthetic configuration and reverses as coverage expands. The selected score there is gain alone. The edit and model-spread penalties should therefore remain inspectable options whose use requires evidence, rather than mandatory markers of confidence.')
json_save(ROOT/'results/paper_claims.json',dict(draft=args.draft,displayed_values=ledger,
    sources={name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in cache},generated_outputs=outputs,
    static_numerical_sources=['configs/study.json','data/manifests','results/audits/reference_checks.json','results/audits/parity_cuda.json'],
    scope='Every generated result value is recorded with its source JSON path or an explicit aggregation. Figure sources are in paper/figures/provenance.json.'))
print('Generated',len(outputs),'LaTeX components and',len(ledger),'traceable value uses; draft=',args.draft)
