"""Generate manuscript results and a value-to-artifact ledger. No invented data."""
from pathlib import Path
import argparse,hashlib,json,sys
import numpy as np
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/'src'))
from iot_repair.experiment import json_save
p=argparse.ArgumentParser();p.add_argument('--draft',action='store_true');args=p.parse_args()
out=ROOT/'paper/generated';out.mkdir(parents=True,exist_ok=True)
cache={};ledger=[];outputs={};section=''
NAMES=['synthetic_32_linear','synthetic_32_nonlinear','synthetic_64_nonlinear','intel','skab']
SHORT=['S32L','S32N','S64N','Intel','SKAB']
MAIN='results/analysis.json';DESIGN='results/dataset_summary.json';CONF='results/confidence_comparisons.json'

def read(path):
    if path not in cache:cache[path]=json.loads((ROOT/path).read_text())
    return cache[path]
def get(path,*keys):
    v=read(path)
    for k in keys:v=v[k]
    return v

def num(path,*keys,d=3,mult=1):
    value=get(path,*keys);rendered='N/A' if value is None else f'{value*mult:.{d}f}'
    ledger.append(dict(output=section,source=path,json_path=list(keys),value=value,multiplier=mult,rendered=rendered))
    return rendered

def derived(value,sources,operation,d=3):
    rendered=f'{value:.{d}f}';ledger.append(dict(output=section,sources=sources,operation=operation,value=float(value),rendered=rendered));return rendered

def write(name,text):
    (out/name).write_text('% Generated by scripts/make_paper.py from saved results.\n'+text+'\n');outputs[name]=hashlib.sha256((out/name).read_bytes()).hexdigest()
def metric(name,method='proposed',kind='observation',key='window_ap',d=3):return num(MAIN,name,'tracks',kind,'methods',method,key,d=d)
def base(name):return get(MAIN,name,'tracks','observation','primary_comparator')
def ci(path,*keys,d=3):return '['+num(path,*keys,'interval',0,d=d)+', '+num(path,*keys,'interval',1,d=d)+']'
def abl(name,variant,kind='observation',key='window_ap'):
    path=f'results/ablations/{name}/analysis.json'
    if not (ROOT/path).exists() or variant not in read(path):
        if args.draft:return r'\textit{pending}'
        raise RuntimeError('Incomplete ablation '+name+'/'+variant)
    return num(path,variant,'metrics',kind,key)
def require(path):
    if not (ROOT/path).exists():
        if args.draft:return False
        raise RuntimeError('Missing required result '+path)
    return True

def table(caption,label,columns,rows,wide=True):
    env='table*' if wide else 'table'
    spacing='' if wide else '\\setlength{\\tabcolsep}{4pt}\n'
    return '\\begin{'+env+'}[t]\n\\centering\\small\n'+spacing+'\\caption{'+caption+'}\\label{'+label+'}\n\\begin{tabular}{'+columns+'}\n\\toprule\n'+'\n'.join(rows)+'\n\\bottomrule\n\\end{tabular}\n\\end{'+env+'}'

def row(label,values):return label+' & '+' & '.join(values)+r' \\'

for name in NAMES:
    assert get(MAIN,name,'tracks','observation','methods','proposed','windows')>0
    if not args.draft:require(f'results/ablations/{name}/complete.json');require(f'results/robustness/{name}/analysis.json')
if not args.draft:
    for path in ['results/native/skab/analysis.json','results/latency_scaling.json','results/audits/portable_models.json','results/audits/inference_repeatability.json','results/audits/pca_scores.json','results/interface/browser_verification.json','results/graph/persistence_audit.json','results/equation_analysis.json','results/cross_type_analysis.json']:require(path)
section='numbers.tex'
write(section,r'\newcommand{\StudyStatus}{'+(r'\begin{center}\textcolor{red}{Layout draft. Secondary results still running.}\end{center}' if args.draft else '')+'}')
section='abstract_results.tex'
write(section, f"A targeted review benefit appeared in the 32-channel nonlinear configuration. Attribution precision among the highest-ranked 10\\% of screened candidates was {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods','proposed','candidate_risk_coverage',0,'precision')} versus {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods',base('synthetic_32_nonlinear'),'candidate_risk_coverage',0,'precision')} for the selected PCA comparator. The paired difference interval was {ci(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.1')}. This benefit reversed at broader coverage. PCA was stronger on the primary observation-detection endpoint in four configurations, with an inconclusive difference on Intel. No clear association-detection advantage was established.")
section='datasets_table.tex';rows=[r'Configuration & Channels / sources & Split unit & Train windows & Dev / cal / test bases & Test missing \\',r'\midrule']
for name,short in zip(NAMES,SHORT):
    rows.append(row(short,[num(DESIGN,name,'channels',d=0)+' / '+num(DESIGN,name,'physical_sources',d=0),
        'trajectory' if name.startswith('synthetic') else 'day' if name=='intel' else 'experiment',num(DESIGN,name,'splits','train','windows',d=0),
        ' / '.join(num(DESIGN,name,'splits',split,'base_windows_selected',d=0) for split in ['development','calibration','test']),num(DESIGN,name,'splits','test','missing_fraction',mult=100,d=1)+r'\%']))
prevalence=[get(DESIGN,n,'association_window_prevalence') for n in NAMES]
write(section,table('Executed partitions. S32L, S32N and S64N are configurations of one synthetic dataset. Each base supplies an unmodified and a corrupted window per eligible controlled task. Observation prevalence is 0.50. Association prevalence ranges from '+derived(min(prevalence),[DESIGN],'minimum association window prevalence')+' to '+derived(max(prevalence),[DESIGN],'maximum association window prevalence')+'. Missingness is measured before injected dropout. Native SKAB process events are evaluated separately.','tab:data','lclrrr',rows))
section='main_table.tex';rows=[row('Method or endpoint',SHORT),r'\midrule',r'\multicolumn{6}{l}{Observation window average precision} \\']
for lag,label in [('1','PCA total error, current'),('4','PCA total error, lagged')]:
    rows.append(row(label,[num('results/pca_total/analysis.json','results',n,'metrics',lag,'window_ap') for n in NAMES]))
for title,method in [('PCA channel maximum, current','pca1'),('PCA channel maximum, lagged','pca4'),('GDN','gdn'),('Diffusion residual','backbone'),('DiffAD adaptation','diffad'),('Deterministic repair','deterministic'),('Witness repair','proposed')]:
    vals=[]
    for name in NAMES:
        m=get(MAIN,name,'selection','pca','1' if method=='pca1' else '4') if method in ('pca1','pca4') else method
        vals.append(abl(name,m) if m=='deterministic' else metric(name,m))
    rows.append(row(title,vals))
rows.append(row(r'Paired difference, 95\% interval', [r'\shortstack{'+num(MAIN,n,'tracks','observation','paired_difference','difference')+r'\\{}'+ci(MAIN,n,'tracks','observation','paired_difference')+'}' for n in NAMES]))
rows.extend([r'\midrule',r'\multicolumn{6}{l}{Association window average precision} \\'])
for title,m in [('Direct edge residual','edge_residual'),('Deterministic repair','deterministic'),('Witness repair','proposed')]:rows.append(row(title,[abl(n,m,'association') if m=='deterministic' else metric(n,m,'association') for n in NAMES]))
rows.append(row(r'Paired difference, 95\% interval',[r'\shortstack{'+num(MAIN,n,'tracks','association','paired_difference','difference')+r'\\{}'+ci(MAIN,n,'tracks','association','paired_difference')+'}' for n in NAMES]))
rows.extend([r'\midrule',row('Observation top-one attribution',[metric(n,key='top1') for n in NAMES]),row('Observation screening recall',[metric(n,key='screening_recall') for n in NAMES])])
write(section,table('Controlled-fault results. Differences use the frozen development-selected comparator, PCA channel maximum for observations and direct residuals for associations. The total-error PCA rows are an additional formula-completeness check with development-selected ranks. GDN, PCA and residual diffusion detectors have no stored-association output. Attribution rows include screening misses. Intervals resample whole source blocks.','tab:main','lrrrrr',rows))
section='results_text.tex'
text=r'Table~\ref{tab:main} answers the primary detection question. The proposed score did not improve observation detection over the development-selected comparator. Its paired average-precision differences were negative with intervals excluding zero in the three synthetic configurations and SKAB. The Intel interval included zero. These results favor retaining PCA as the inexpensive first detector. Nonlinear responses alone did not make the linear baseline ineffective.'+'\n\n'
text+='Witness repair did improve detection relative to the neural comparators in the nonlinear synthetic configurations. In S32N, its average-precision advantage over GDN was '+num(CONF,'results','synthetic_32_nonlinear','observation','paired_window_ap_by_comparator','gdn','difference')+' with interval '+ci(CONF,'results','synthetic_32_nonlinear','observation','paired_window_ap_by_comparator','gdn')+'. The corresponding difference from the same-backbone residual detector was '+num(CONF,'results','synthetic_32_nonlinear','observation','paired_window_ap_by_comparator','backbone','difference')+' with interval '+ci(CONF,'results','synthetic_32_nonlinear','observation','paired_window_ap_by_comparator','backbone')+'. These secondary comparisons support testing separate witnesses, while the stronger PCA result limits their practical advantage.'+'\n\n'
text+=f"There was a narrower review benefit in S32N. At 10\\% screened-candidate coverage, precision was {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods','proposed','candidate_risk_coverage',0,'precision')} for witness repair and {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods',base('synthetic_32_nonlinear'),'candidate_risk_coverage',0,'precision')} for PCA. The paired precision difference was {num(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.1','difference')} with interval {ci(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.1')}. At 25\\% coverage the difference was {num(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.25','difference')} with interval {ci(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','precision_difference_at_0.25')}. The advantage therefore concerns a limited review budget, not more complete detection. These secondary intervals are descriptive and are not adjusted for multiple comparisons.\n\n"
text+=f"On the same S32N candidate population, fitted-probability Brier loss was {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods','proposed','probability_evaluation','brier')} versus {num(MAIN,'synthetic_32_nonlinear','tracks','observation','methods',base('synthetic_32_nonlinear'),'probability_evaluation','brier')} for PCA. The paired difference interval was {ci(CONF,'results','synthetic_32_nonlinear','observation','paired_secondary_endpoints','brier_main_minus_comparator')}. Lower probability error does not recover faults omitted by screening. Observation screening recall ranged from {derived(min(get(MAIN,n,'tracks','observation','methods','proposed','screening_recall') for n in NAMES),[MAIN],'minimum proposed observation screening recall')} to {derived(max(get(MAIN,n,'tracks','observation','methods','proposed','screening_recall') for n in NAMES),[MAIN],'maximum proposed observation screening recall')}.\n\n"
text+=r'Association differences all had intervals containing zero. The mask procedure supplies an inspectable alternative explanation but did not establish better association detection than direct prediction residuals. Marginally matched relation faults still had joint metadata shortcuts. The metadata-only classifier obtained ROC area '+num('results/audits/association_metadata.json','skab','metadata_only_roc_auc')+r' on SKAB. This limits claims about relation reasoning despite preserved degrees and attribute marginals.'+'\n\n'
cross='results/cross_type_analysis.json'
text+='Joint use exposed a second limit. Among S32N windows with only injected reading faults, the association window alarm fired in '+num(cross,'results','synthetic_32_nonlinear','alarm_table','observation','association_window_alert')+' of cases at nominal 5\\%. Both candidate types were accepted in '+num(cross,'results','synthetic_32_nonlinear','alarm_table','observation','both_candidate_types_accepted')+'. A strong relation-mask score therefore cannot identify a relation fault exclusively. The review-precision comparison above uses reading-fault and unmodified windows. Its fitted probabilities do not describe an arbitrary mixture of competing fault types.'+'\n\n'
text+=f"Calibration had finite resolution. Intel had only {num(MAIN,'intel','tracks','observation','methods','proposed','null_reference_units',d=0)} reference windows, so its minimum window tail was {num(MAIN,'intel','tracks','observation','methods','proposed','null_resolution')}. The Intel 5\\% window threshold therefore cannot raise an alarm. No configuration could raise a window alarm at the nominal 1\\% level. At 5\\%, observed false-positive fractions for witness repair were "+', '.join(num(MAIN,n,'tracks','observation','methods','proposed','operating_points',1,'fpr') for n in NAMES)+r' in table order. Figure~\ref{fig:confidence} keeps the measured families separate. The labeled probability fit and the null-tail test answer different questions.'
write(section,text)
section='ablation_table.tex';rows=[row('Score or inference variant',SHORT),r'\midrule']
for title,m in [('Selected score','proposed'),('Gain only','R_only'),(r'Fixed $\kappa=1,\lambda=0.2$','fixed_penalties'),('No spread penalty','no_uncertainty'),('No edit penalty','no_cost'),('Supervised terms','supervised_terms')]:rows.append(row(title,[metric(n,m) for n in NAMES]))
for title,v in [('Deterministic replacements','deterministic'),('No graph conditioning','no_graph'),('Visible witnesses (unsafe)','no_witness_separation'),('Channel groups (unsafe)','no_provenance_grouping'),('Count known copies (unsafe)','no_provenance_deduplication')]:rows.append(row(title,[abl(n,v) for n in NAMES]))
rows.append(r'\midrule')
rows.append(row(r'Selected $(\kappa,\lambda)$',['('+num(MAIN,n,'selection','kappa',d=2)+', '+num(MAIN,n,'selection','lambda',d=2)+')' for n in NAMES]))
write(section,table('Observation window average precision for the equation and inference ablations. Every variant uses the same test cases and its own reference scores on the common calibration blocks. Unsafe variants are diagnostics. Zero selected penalties produce identical rows by construction.','tab:ablation','lrrrrr',rows))
section='ablation_text.tex'
text=r'Table~\ref{tab:ablation} separates arithmetic correctness from predictive usefulness. Development selection set the edit penalty to zero in every configuration except Intel and set both penalties to zero in S32N. The positive Intel cost penalty did not change test average precision at the displayed precision. These findings do not support the claim that every score term is needed. A single-edge cost is constant within a fixed graph, so it cannot improve the order of edges in that window.'+'\n\n'
text+=f"The spread penalty had a practical threshold effect on controlled SKAB windows. Gain alone had false-positive fraction {num(MAIN,'skab','tracks','observation','methods','R_only','operating_points',1,'fpr')} at nominal 5\\%, compared with {num(MAIN,'skab','tracks','observation','methods','proposed','operating_points',1,'fpr')} for the selected score. Fault recall also fell from {num(MAIN,'skab','tracks','observation','methods','R_only','operating_points',1,'recall')} to {num(MAIN,'skab','tracks','observation','methods','proposed','operating_points',1,'recall')}. Conservatism here does not imply accurate diagnosis.\n\n"
if all((ROOT/f'results/ablations/{n}/complete.json').exists() for n in NAMES):
    text+='Deterministic replacement reached '+abl('synthetic_32_nonlinear','deterministic')+' AP in S32N, close to the sampled score. Removing graph conditioning gave '+abl('synthetic_32_nonlinear','no_graph')+' because this architecture then has no path by which editing one channel changes another channel\'s prediction. The result tests a necessary information path, not the superiority of a particular graph learner. Witness visibility and counted copies are deliberately invalid evidence procedures. Their results are retained even when a metric improves. Such improvement cannot establish independent support.'+'\n\n'
else:text+=r'\textcolor{red}{Secondary inference ablations are still running in this layout draft.}'+'\n\n'
text+=f"The production audit independently recomputed {num('results/audits/production_equations.json','candidates',d=0)} candidate scores from saved samples across {num('results/audits/production_equations.json','cases',d=0)} cases. The largest absolute arithmetic discrepancy was "+derived(get('results/audits/production_equations.json','max_absolute_error')*1e15,['results/audits/production_equations.json'],'maximum error multiplied by 10^15',d=2)+r'$\times10^{-15}$. This verifies implementation, not the research hypotheses. Figure~\ref{fig:equations} examines paired variants, sampling variability, contaminated conditioning and measured runtime.'
write(section,text)
section='robustness_text.tex';eq='results/equation_analysis.json'
text='S32N observation AP was '+num(MAIN,'synthetic_32_nonlinear','tracks','observation','predefined_strata','known_families','proposed','window_ap')+' on familiar corruption families and '+num(MAIN,'synthetic_32_nonlinear','tracks','observation','predefined_strata','heldout_families','proposed','window_ap')+' on held-out families. PCA reached '+num(MAIN,'synthetic_32_nonlinear','tracks','observation','predefined_strata','heldout_families','comparator','window_ap')+' on the latter. In the two shifted test trajectories, the respective AP values were '+num(MAIN,'synthetic_32_nonlinear','tracks','observation','predefined_strata','heldout_regime','proposed','window_ap')+' and '+num(MAIN,'synthetic_32_nonlinear','tracks','observation','predefined_strata','heldout_regime','comparator','window_ap')+'. These small strata do not establish robust transfer.'+'\n\n'
text+='The gain is also sensitive to context. Its Spearman correlation with initial witness loss was '+num(MAIN,'intel','score_terms','observation','gain_initial_loss_spearman')+' on Intel, and its correlation with channel degree was '+num(MAIN,'skab','score_terms','observation','gain_degree_spearman')+' on SKAB. Thus a large gain can partly reflect where improvement was possible, rather than fault identity alone.'+'\n\n'
if require(eq):
    stress='results/robustness/synthetic_32_nonlinear/analysis.json'
    reversal='synthetic_32_nonlinear'
    text+='A saved development pair illustrates the ranking inequality. Its gain difference was '+num(eq,reversal,'ranking_reversal','gain_difference',d=4)+', while its combined penalty difference at $\\kappa=1,\\lambda=0.2$ was '+num(eq,reversal,'ranking_reversal','penalty_difference',d=4)+'. The score difference became '+num(eq,reversal,'ranking_reversal','score_difference_at_kappa1_lambda02',d=4)+', reversing the order. This arithmetic example explains a ranking change without establishing a detection gain. '
    sensitivity=get(eq,reversal,'sampling_sensitivity')
    se=[np.median([r['median_monte_carlo_se'] for r in sensitivity if r['E']==3 and r['M']==m and r['L']==8 and r['amp']]) for m in [2,16]]
    text+='Across the three development sensitivity windows, the median sampling diagnostic fell from '+derived(se[0],[eq],'median case diagnostic at E3 M2 L8 neural autocast',d=4)+' at $M=2$ to '+derived(se[1],[eq],'median case diagnostic at E3 M16 L8 neural autocast',d=4)+' at $M=16$. More draws reduce this source of variability without creating independent model members.'+'\n\n'
    text+='In the targeted S32N conditioning experiment, primary-target top-one attribution changed from '+num(stress,'conditions','conditioning_source_contamination/0.0','primary_target_top1')+' without additional corruption to '+num(stress,'conditions','conditioning_source_contamination/0.5','primary_target_top1')+' when half of the eligible conditioning channels were shifted. Each condition used '+num(stress,'conditions','conditioning_source_contamination/0.0','cases',d=0)+' evenly spaced reference windows. Additional corrupted channels were distractors for this endpoint, not relabeled primary targets. These runs diagnose dependence on conditioning quality rather than estimate a field failure rate.'+'\n\n'
    text+='At that contamination level, screening retained the primary target in '+num(stress,'conditions','conditioning_source_contamination/0.5','primary_target_screened')+' of windows. PCA top-one attribution was '+num(stress,'conditions','conditioning_source_contamination/0.5','baseline_primary_target_top1',base('synthetic_32_nonlinear'))+'. Under the separate requested 30\\% graph-error condition, witness repair retained '+num(stress,'conditions','graph_error/0.3','primary_target_top1')+' top-one attribution. Unknown association-copy aliases retained '+num(stress,'conditions','unknown_provenance_association_copies/all','primary_target_top1')+' in this small sample, which does not extend known-copy invariance to unknown identities.'+'\n\n'
    text+='The one-source condition withheld high-confidence attribution in all '+num(stress,'conditions','single_source_support/all','selected_primary_windows_abstained',d=0)+' windows. Its separately marked diagnostic top-one rate was '+num(stress,'conditions','single_source_support/all','single_group_diagnostic_top1')+'. Dropout produced '+num(stress,'conditions','missingness/all','availability_alerts',d=0)+' availability alerts while numeric replacement abstained. Training with 10\\% contaminated windows gave primary-target top-one attribution '+num(stress,'conditions','training_contamination/0.1','primary_target_top1')+'. The original normalizer and decision parameters remained fixed.'+'\n\n'
    controls=get(stress,'physical_controls');accepted=sum(len(v['accepted_hypotheses']) for v in controls.values())
    text+='The common-mode construction supplies exactly the same observations under a physical-event story and a coordinated-fault story. Together with the changed-response control it produced '+derived(accepted,[stress],'sum accepted hypotheses in two physical controls',d=0)+' accepted candidate explanations in S32N. An accepted repair is therefore not a unique physical diagnosis. The saved latent trajectories expose this ambiguity.'+'\n\n'
text+='Ordinary CUDA reductions were not bitwise repeatable. Saved predictive samples are the authoritative inputs to the arithmetic audit. Replaying portable weights against the original checkpoints with deterministic reductions gave exact predictive-array agreement. Separate deterministic checks also preserved the trained model output after adding known copies. This distinguishes evidence invariance from floating-point execution order.'
write(section,text)
section='native_text.tex';path='results/native/skab/analysis.json'
if require(path):
    d=read(path);methods=d['methods'];selected=base('skab')
    text=f"Native SKAB evaluation covered {num(path,'methods','gdn','windows',d=0)} windows from {num(path,'methods','gdn','experiments',d=0)} disjoint test experiments. GDN had process-window average precision {num(path,'methods','gdn','window_ap')}, event recall {num(path,'methods','gdn','event_recall')} and false-positive fraction {num(path,'methods','gdn','achieved_fpr')} at nominal 5\\%. Median delay among detected events was {num(path,'methods','gdn','median_detected_event_delay_seconds',d=1)} seconds, with {num(path,'methods','gdn','censored_events',d=0)} undetected events. It retained {num(path,'methods','gdn','process_alerts_retained_during_attribution_abstention',d=0)} process alerts while attribution abstained. These labels support no sensor-localization claim.\n"
    rows=[r'Method & Window AP & Event recall & False events/h \\',r'\midrule']
    for label,m in [('PCA, lag embedding',selected),('GDN','gdn'),('Diffusion residual','backbone'),('DiffAD adaptation','diffad')]:rows.append(row(label,[num(path,'methods',m,'window_ap'),num(path,'methods',m,'event_recall'),num(path,'methods',m,'false_alarm_events_per_hour',d=2)]))
    text+='\n'+table('Native SKAB process events. Thresholds come from the frozen calibration protocol. Event delay is measured at the actual decision time without point adjustment.','tab:native','lrrr',rows,False)
else:text=r'\textcolor{red}{Native SKAB process evaluation is pending in this layout draft.}'
write(section,text)
section='cost_text.tex';path='results/latency_scaling.json'
if require(path):
    runs=get(path,'runs');sources=[path,MAIN]
    for n in ['synthetic_32_nonlinear','synthetic_64_nonlinear']:
        assert len([r for r in runs if r['dataset']==n and r['tested_candidates']==8])==5
    seconds=[np.median([r['elapsed_seconds'] for r in runs if r['dataset']==n and r['tested_candidates']==8]) for n in ['synthetic_32_nonlinear','synthetic_64_nonlinear']]
    memory=max(r['peak_allocated_bytes'] for r in runs)/2**30
    text='On the existing RTX PRO 4500 Blackwell GPU, median warm inference for eight tested hypotheses was '+derived(seconds[0],sources,'median 32-channel warm runs, 8 candidates')+' s for S32N and '+derived(seconds[1],sources,'median 64-channel warm runs, 8 candidates')+' s for S64N. Peak allocated memory across the candidate-scaling runs was '+derived(memory,sources,'maximum allocated bytes / 2^30',d=2)+' GiB. Timings include screening, transfer, scoring and tail calculation, and exclude loading and database writes. They describe the saved window, not end-to-end service guarantees. '
    bt=get(MAIN,'synthetic_32_nonlinear','costs','baseline_timing');pca=bt[base('synthetic_32_nonlinear')]['inference_seconds_per_window']
    text+='The same configuration required '+derived(pca*1e3,[MAIN],'PCA inference seconds per window times 1000',d=3)+' ms per window for PCA and '+derived(bt['gdn']*1e3,[MAIN],'GDN ensemble batched inference seconds per window times 1000',d=3)+' ms for GDN in batched comparator evaluation. These baseline timings use a different batching regime and are reported as measured, not as a hardware-independent speedup. '
    training=[r for n in NAMES for r in get(MAIN,n,'costs','training')]
    text+='The final neural training records total '+derived(sum(r['gpu_hours'] for r in training),[MAIN],'sum final recorded neural training GPU hours',d=3)+' GPU hours, excluding tuning, pilot work and experiment inference. Base windows use a 32-sample stride, corresponding to 32 s for the simulator and SKAB and 160 min for Intel. Controlled tests subsample these windows. Native SKAB evaluation retains the full test sequence at that stride. The stride and eight-step target interval limit temporal resolution.'
else:text=r'\textcolor{red}{Uncontended inference benchmarking is pending in this layout draft.}'
write(section,text)
section='network_caption.tex';b='results/graph/synthetic_32_nonlinear_illustration.json';case=get(b,'case')
write(section,'Saved S32N case from '+case['block'].replace('_',r'\_')+', sample interval ['+num(b,'case','start',d=0)+', '+num(b,'case','stop',d=0)+'). Only a '+case['fault']['family']+' reading fault was injected. The strong alternative association mask illustrates diagnostic ambiguity. Graph version '+r'\texttt{'+case['graph']['version']+'}'+'. Arrows predict the labeled target at the stated lag in seconds. All highlighted sources and witnesses are retained. Context is a stored-relation spanning forest and layout uses no fault labels. This selected illustration does not estimate performance.')
section='conclusion_results.tex'
write(section,r'The experiments support a bounded role for witness repair as a review mechanism. They do not support replacing PCA for broad observation detection or direct relation residuals for association detection. A measured benefit appears at a small review budget in one nonlinear synthetic configuration and reverses as coverage expands. The selected score there is gain alone. The edit and model-spread penalties should therefore remain inspectable options whose use requires evidence, rather than mandatory markers of confidence.')
json_save(ROOT/'results/paper_claims.json',dict(draft=args.draft,displayed_values=ledger,
    sources={name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in cache},generated_outputs=outputs,
    static_numerical_sources=['configs/study.json','data/manifests','results/audits/reference_checks.json','results/audits/parity_cuda.json'],
    scope='Every generated result value is recorded with its source JSON path or an explicit aggregation. Figure sources are in paper/figures/provenance.json.'))
print('Generated',len(outputs),'LaTeX components and',len(ledger),'traceable value uses; draft=',args.draft)
